### ISSUE TITLE
Using a transaction for testing

### ISSUE THREAD

**Issue by ghost** [mikeball/foundation#14]
I haven't quite wrapped my head around wrapping foundation database transactions with one of my own.

I'm trying to create a test fixture that looks like this:

```clj
(ns vsa-sql-management.test-helpers
  (:require [clojure.java.jdbc :as jdbc]
            [taoclj.foundation :as pg]
            [environ.core :refer [env]]))

(declare ^:dynamic *store*)

(def test-db-spec
  {:classname "org.postgresql.Driver"
   :subprotocol "postgresql"
   :subname "//127.0.0.1:5432/vsa_test"
   :user "postgres"})

(defn db-transaction-fixture [f]
  (jdbc/with-db-transaction [store test-db-spec]
    (jdbc/db-set-rollback-only! store)
    (binding [*store* store] (f))))
```

Ideally, I can be passing in the dynamic store variable into a ``pg/trx->`` call so my tests know that the transaction should be rolled back. However, when I write a test like this:

```clj
(ns vsa-sql-management.seeders.vsa-questionnaire-template-test
  (:require [vsa-sql-management.seeders.vsa-questionnaire-template :as sut]
            [vsa-sql-management.test-helpers :refer [*store* db-transaction-fixture]]
            [taoclj.foundation :as pg]
            [clojure.test :as t]
            [environ.core :refer [env]]))

(t/use-fixtures :each db-transaction-fixture)

(t/deftest seed-test
  (t/testing "seeds database with questions"
    (pg/trx-> sut/vsa-db (pg/insert :people {:name "nick"}))
    (t/is (= 1 (pg/trx-> sut/vsa-db (pg/select :people {:name "nick"}))))))
```

I still see the created person record in my test database. I'm sure there's something simple that my stupid self is missing. Any help would be appreciated! I think if I figure out the proper place to pass the ``*store*`` variable to, I'll be all good.

**Comment by ghost** [comment]
such a n00b to clojure still, but I'll try messing around with these lines for both my issues: https://github.com/mikeball/foundation/blob/b59de02024dfb6c52c9e1021db4d255850f68dcc/src/taoclj/foundation.clj#L217-L223

**Comment by mikeball** [comment]
Yeah, there's not a way to manually control transactions just yet. I have some thoughts just not implemented yet.
