### ISSUE TITLE
Fail loudly

### ISSUE THREAD

**Issue by ghost** [mikeball/foundation#15]
When I try to execute a query that creates a database error (e.g. causing Postgres to print its own STDERR in its logs), it'd be nice to see the exception returned to be in the clj code instead of just ``nil`` (e.g. null constraints, foreign keys, etc.). If you like this idea, where should I look to implement it?

**Comment by mikeball** [comment]
I don't know about this one way or another. I believe that the thought was to allow user to pass an exception handler to the qry-> and trx-> macros.
