### ISSUE TITLE
Debug output is on by default

### ISSUE THREAD

**Issue by amacdougall** [mikeball/foundation#2]
# Description

Something in Foundation's database code is emitting debug statements to the REPL.
# Steps to Reproduce

Run a Foundation query in the REPL.
# Expected Behavior

Query runs silently if there are no errors.
# Actual Behavior

On first query:

```
(pg/qry-> conn (get-users {:limit 10 :offset 0}))
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/amacdougall/.m2/repository/ch/qos/logback/logb
ack-classic/1.1.2/logback-classic-1.1.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/amacdougall/.m2/repository/org/slf4j/slf4j-sim
ple/1.7.13/slf4j-simple-1.7.13.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
16:05:48.528 [nREPL-worker-1] DEBUG i.n.u.i.l.InternalLoggerFactory - Using SLF4J as the default logging framework
16:05:48.534 [nREPL-worker-1] DEBUG i.n.c.MultithreadEventLoopGroup - -Dio.netty.event
LoopThreads: 8
16:05:48.548 [nREPL-worker-1] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Bu
ffer.address: available
16:05:48.548 [nREPL-worker-1] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Un
safe.theUnsafe: available
<much more output omitted>
```

On subsequent queries, debug statements related to thread pooling. My DB config has `pooling: false`, so this is probably just related to standard JDBC.

```
16:08:55.584 [threadDeathWatcher-2-3] DEBUG io.netty.buffer.PoolThreadCache - Freed 8 thread-local buffer(s) from thread: PG-JDBC EventLoop (1)
```
# Developer Analysis

Debug logging levels should be configurable, and have a high threshold (log only on warning or errors, perhaps) by default.

**Comment by mikeball** [comment]
Can you do a "lein deps :tree" in the project root and see if there is is anything for org.slf4j/slf4j-simple? I suspect that there's an older version of this dependency in your tree, which was causing me issues as well. I actually included it in https://github.com/mikeball/foundation/blob/master/project.clj to get it to stop. I think there's an issue with an earlier version of the SLF4J logger that causes this overzealous logging.

**Comment by amacdougall** [comment]
These are the only references to it in that output:

```
[org.taoclj/foundation "0.1.0"]
   [com.impossibl.pgjdbc-ng/pgjdbc-ng "0.6"]
     [io.netty/netty-all "4.0.32.Final"]
   [com.zaxxer/HikariCP "2.4.3"]
     [org.slf4j/slf4j-api "1.7.12"]
   [org.slf4j/slf4j-simple "1.7.13"]
```

Is that helpful?

**Comment by mikeball** [comment]
Thanks for this report. I've removed the project reference to org.slf4j/slf4j-simple which was actually put in place to stop logging like this that was coming from an older version in one of the deps. The dep has since updated and the reference is no longer necessary.
