### ISSUE TITLE
NPE attempting SELECT query

### ISSUE THREAD

**Issue by amacdougall** [mikeball/foundation#3]
I ​was able to use an insert query from a template file to write to my database, but when I tried a select query, I got this result:

```
=> NullPointerException   clojure.lang.Reflector.invokeNoArgInstanceMember (Reflector.java:301)
```

I tried this query:

``` clojure
```

(pg/qry-> conn (pg/select :users {}))

``````
That query should simply evaluate to `SELECT * FROM users;`, right? I did get the same result when I used a template query:
```sql
SELECT * FROM users LIMIT :limit OFFSET :offset;
``````

``` clojure
(pg/qry-> conn (get-users {:offset 0 :limit 30}))
```

Any idea what I'm doing wrong? For completeness, here's my DB spec:

``` clojure
; it actually comes from a profiles.clj thing, but these are the values:
(def datasource
  {:host "localhost"
    :port 5432
    :database "<known-good value>"
    :username "<known-good value>"
    :password "<<known-good value>"
    :pooled false}}
```

And I'm just doing:

``` clojure
(pg/def-datasource conn datasource)
```

**Comment by mikeball** [comment]
Thanks for the report! 

Ok, at first I read this wrong. I've just tested this code and it should work.

``` clojure
(def datasource
   {:host "localhost"
    :port 5432
    :database "examples_db"
    :username "examples_app"
    :password "password"
    :pooled false})

(pg/def-datasource conn datasource)

(pg/qry-> conn 
          (pg/select :users {}))

```
- The def-datasource a JDBC datasource, in this case a non-pooled one. The qry-> macro internally handles the opening/closing of connections for you.

**Comment by mikeball** [comment]
I'm curious, what version of java and clojure are you using?

**Comment by amacdougall** [comment]
I'm sorry, I wasn't clear enough—I think I'm defining the datasource correctly. Here's the actual code:

``` clojure
(ns raiseyourgame.db.core
  (:require
    [clojure.java.jdbc :as jdbc]
    [taoclj.foundation :as pg]
    [environ.core :refer [env]]))

; this is where the datasource map actually comes from
(pg/def-datasource conn (env :datasource))

(pg/def-query create-user! {:file "sql/user/create_user.sql"})
(pg/def-query get-users {:file "sql/user/get_users.sql"})
; rest of query templates...
```

That's what I get for omitting important lines. But also note that I _was_ able to insert a row using this:

``` clojure
(pg/qry-> conn (create-user! user-values))
```

That query returned the number of rows affected, and I confirmed in psql that the row was created exactly as I expect. This suggests that the datasource definition was a success.

I'm on Clojure 1.7.0, and upgraded to Java 8 in response to a compile error about the new Instant type.

**Comment by mikeball** [comment]
No problem, I just read it too quickly and just want to get you up and running. 

I don't see anything wrong with what you're doing, so I just created a repo with the code as close as I could get for your situation, but using the examples database schema linked below.. 

https://github.com/mikeball/raiseyourgame

Can you git clone that and does that run for you? Can you re-create the error in that repo?

Do you have any placeholders (eg :users) in sql comments in your query file? That might cause an issue, there was something I can't recall at the moment, where having keywords in sql comments conflicted with the parser.

[1] https://github.com/mikeball/foundation/blob/master/resources/examples.sql

**Comment by amacdougall** [comment]
Oh, the placeholder thing may be the issue; I copied my YeSQL statements directly, and they included doc comments which used the placeholders. I'll check it out tonight when I'm back at my personal laptop.

I copied everything from [this file](https://github.com/amacdougall/raiseyourgame/blob/master/resources/sql/users.sql) into the individual query files Foundation wants, and I can see that the user creation query had no placeholders in its doc comment, but the user listing does, so this theory holds a lot of water.

**Comment by amacdougall** [comment]
Your example definitely works; clearly the problem is on my side. `lein repl` was giving me some compile errors in some namespaces, but I did not think they were critical as long as I could load the `db.core` namespace and test Foundation. Perhaps I was wrong! I'm still learning about Clojure... painfully, in many cases.

**Comment by amacdougall** [comment]
### Query Update

I cleaned up the compile errors, but sadly, I'm still getting the same error when I run the `get-users` query from the REPL.

I've pushed my current Foundation integration WIP to the `foundation` branch of my project. If you'd like, you can clone https://github.com/amacdougall/raiseyourgame, switch to that branch, and run `lein repl`; then, in the REPL, do this:

``` clojure
; minimum ns for this demo
(ns raiseyourgame.db.core
  (:require [taoclj.foundation :as pg]))

(pg/def-datasource conn <your data definition>)

; Note that get-users just gets * from the users table. Easy to alter to hit your test DB.

; Note that my create-user! query works fine!

(pg/qry-> conn (get-users {:offset 0 :limit 10}))
```

Unfortunately, you may get this:

```
; => NullPointerException   clojure.lang.Reflector.invokeNoArgInstanceMember (Reflector.java:301)
```

I tried it again after removing parameters from the SQL entirely. I also tried using `find-users-by-username`, and got the same result. Maybe only select queries are in trouble?

### Update Queries

To test that idea, I tried doing an update query, but when I tried passing a `nil` value for a nullable column, I got `Exception Parameter type not mapped!`. Looking at [the Foundation source](https://github.com/mikeball/foundation/blob/master/src/taoclj/foundation/writing.clj#L25), it looks like you're inferring the column type from the value type—after all, given an untyped map of column names to update values, how are you going to know which `PreparedStatement.set*` function to use? And according to the [jdbc docs](https://docs.oracle.com/javase/7/docs/api/java/sql/PreparedStatement.html), you have to provide the SQL column type when calling `setNull`, which is irritating to no end.

It may not be idiomatic Clojure, but I would be totally okay with requiring a more elaborate `def-query`, if needed. `(def-query update-user! {:file "path.sql", :active java.lang.Boolean, :username java.lang.String, ...})` is not too much to ask if it's the only way to get the right effect.

**Comment by mikeball** [comment]
Ok, I think I tracked this one down. It was the null values in the last_login timestamptz columns. I hadn't yet handled null values for timestamptz.

I actually worked through your entire users query file, with your database structure and you can see a running implementation using foundation.
https://github.com/mikeball/raiseyourgame
https://github.com/mikeball/raiseyourgame/blob/master/src/raiseyourgame/db/core.clj

I pushed a new foundation version that should resolve this issue, as well as clean up some other issues.
[org.taoclj/foundation "0.1.1"]

Can you let me know if the fixes turn out for you?

And thanks for trying foundation out!

**Comment by mikeball** [comment]
> you have to provide the SQL column type when calling setNull, which is irritating to no end.

Oh yeah, that certainly throws a wrench into the way I'm currently handing mapping. I had been sort of falling on the side of not specifying schema explicitly but this might change things.

I need to look and see what yesql/hugsql are doing to handle this.

So handle this properly, if I can't find a workaround, we must specify the sql schema types in some fashion. If that's the case, the only question is do we specify it at a global level for use across the application(e.g. validation/test.check/etc..), or at the query level where necessary as you suggest.

**Comment by amacdougall** [comment]
YeSQL just generates a JDBC query template string and populates it on the fly for each query, as far as I can tell from [the relevant part of the code](https://github.com/krisajenkins/yesql/blob/master/src/yesql/generate.clj#L94).

I'm already using Prismatic Schema in a limited way, so it would be fairly convenient for me to just apply it elsewhere. But then you get into the business of mapping Schema types to Java types, and so on. If you need to declare a schema, I guess do it as simply as possible.

From a data modeling standpoint, it makes perfect sense for a timestamptz column to be nullable: if an event has literally never occurred, it cannot have any sensible timestamp.

**Comment by amacdougall** [comment]
Hey, the `get-users` query works just fine now! Thanks! You can consider this issue resolved.

Also, sorry I'm shaking out so many issues—but I guess no amount of testing can prepare a project for the relentless punishment dished out by end users.

**Comment by mikeball** [comment]
> Also, sorry I'm shaking out so many issues—but I guess no amount of testing can prepare a project for the relentless punishment dished out by end users.

No worries, it definitely needs this, and I'm sorry you hit these issues. Thanks for trying it out!

**Comment by mikeball** [comment]
> you have to provide the SQL column type when calling setNull, which is irritating to no end.

Quick update, I moved over to a protocol based mapping, added tests for null insert/updates and the null problem should now be resolved, and we don't need to provide the sql column type.

**Comment by mikeball** [comment]
> Oh, the placeholder thing may be the issue; I copied my YeSQL statements directly, and they included doc comments which used the placeholders. I'll check it out tonight when I'm back at my personal laptop.

Another update, I've updated parser to ignore all comments now.

**Comment by amacdougall** [comment]
Interesting! I'll give it a try soon. Sorry I didn't respond earlier—I've been away from the world of computers for the past week. Thanks for your hard work on this!

**Comment by amacdougall** [comment]
This definitely works for my standard case—but I'm still not able to run my tests, which make heavy use of `clojure.java.jdbc/with-db-transaction` and `clojure.java.jdbc/db-set-rollback-only!`. I'll post a separate issue, though I hope there's simply a workaround I haven't noticed.
