### ISSUE TITLE
Exception compiling during lein uberjar when :pooled is true

### ISSUE THREAD

**Issue by adwelly** [mikeball/foundation#9]
When I have a datasource:

```
(pg/def-datasource lw-db
                   {:host     "localhost"
                    :port     5432
                    :database "andy"
                    :username "andy"
                    :pooled   true})
```

and I try to create a jar file with lein uberjar, I get a null pointer exception during the compile:

```
$ lein uberjar
Compiling lwchallenge.core
WARNING: update already refers to: #'clojure.core/update in namespace: taoclj.foundation, being replaced by: #'taoclj.foundation/update
java.lang.NullPointerException, compiling:(core.clj:24:1)
Exception in thread "main" java.lang.NullPointerException, compiling:(core.clj:24:1)
    at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3657)
    at clojure.lang.Compiler$IfExpr.eval(Compiler.java:2697)
.....
Caused by: java.lang.NullPointerException
    at java.util.Hashtable.put(Hashtable.java:459)
    at com.zaxxer.hikari.HikariConfig.addDataSourceProperty(HikariConfig.java:294)
    at taoclj.foundation.datasources$create_pooled_datasource.invokeStatic(datasources.clj:27)
    at taoclj.foundation.datasources$create_pooled_datasource.invoke(datasources.clj:26)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3652)
    ... 36 more
```

Something going wrong at com.zaxxer.HikariConfig.

Lein is set up to use clojure 1.8.0 but the same problem occurs with clojure 1.7.0.

```
(defproject lwchallenge "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [org.clojure/data.xml "0.0.8"]
                 [org.taoclj/foundation "0.1.3"]
                 [clj-time "0.11.0"]
                 [org.slf4j/slf4j-log4j12 "1.7.1"]] ; <- I seem to need this when :pooled is true as well
  :main ^:skip-aot lwchallenge.core
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all}})
```

Any idea what might be going on? I've not looked at Hikarai before.

**Comment by mikeball** [comment]
Hi thanks for the descriptive bug report, I was able to get the same error.

It looks like we can get the project to compile if we remove the :aot profile setting for uberjar.

`:profiles` {:uberjar {:aot :all}}

That said, it would be good to support :aot for uberjars. I think the root problem is due to the attempt to create the HikariDataSource object, which is being created at compile time because of :aot.

[(https://github.com/mikeball/foundation/blob/master/src/taoclj/foundation/datasources.clj#L27)
](https://github.com/mikeball/foundation/blob/master/src/taoclj/foundation/datasources.clj#L27)

I suspect to support :aot for uberjars, this needs to be made lazy so that it's not executed until runtime. 

PS Hikari is an awesome connection pool, which is why I've bundled it to make it trivial to enable because most every app needs pooling. [http://brettwooldridge.github.io/HikariCP/](http://brettwooldridge.github.io/HikariCP/)

**Comment by adwelly** [comment]
I think HikariCP is a very important part of this - one of the big
potential advantages of Foundation.

Unfortunately - digging a little deeper, I can't seem to make any potential
workarounds work either.

If you completely remove the profile the code will compile but not run (I
only have one namespace).
If you split the namespace into two, put the datasource into the second
one, require it from the first but only :aot the first you get an NPE.
If you use the two namespace trick but dynamically require the second
namespace and use resolve to find the datasource, you get an NPE.
If you run it from the repl, the moment the compiler tries to compile the
def-datasource, you get an NPE.

As a final experiment, I tried embedding the def-datasource call in a new
connect function, this would compile the call to def-datasource and return
it but would not run it. Running it dynamically in the repl also causes an
NPE.

So I think the problem I am facing is that simply setting :pooled to true
is not sufficient, Hikari is expecting something else to be in place first.

Unfortunately I can't really share source code demonstrating all this -
there needs to be a psql running somewhere with databases, tables etc. In
essence though, all I am doing is running a select query against a simple
table. If pooling is off all is well, if it's on Hikari blows up.

**Comment by mikeball** [comment]
I can't seem to re-create the NPE, so I created a bare project that does seem to work even with uberjar and aot. Is this bare project able to run/compile/uberjar successfully for you?

[https://github.com/mikeball/foundation-issue9](https://github.com/mikeball/foundation-issue9)

If not, this might be a Hikari version issue. Can you check

`lein` deps :tree

and tell me what version of Hikari is being used? Here's the version that I've been testing on.

`[com.zaxxer/HikariCP` "2.4.3"]

Again, sorry for the problems.

**Comment by adwelly** [comment]
..it doesn't compile, but I think the issue is different in this case I get
a missing java.time.Instant when I try to uberjar the issue9.core example:

Tivoli:foundation-issue9-master andy$ lein uberjar

Compiling issue9.core

java.lang.ClassNotFoundException: java.time.Instant,
compiling:(taoclj/foundation/writing.clj:29:1)

Exception in thread "main" java.lang.ClassNotFoundException:
java.time.Instant, compiling:(taoclj/foundation/writing.clj:29:1)

> If not, this might be a Hikari version issue. Can you check
> 
> lein deps :tree

As I was in a bit of a hurry, I swapped out foundation for clojure.jdbc pro
tem. I'll have some time to try again over the weekend and get back to you
on this. No need to apologise for issues - it's all voluntary stuff :-)

Andy

**Comment by mikeball** [comment]
java.time.Instant is only present in java 8. Are you using java 1.7?

**Comment by mikeball** [comment]
I am going to close this issue, because I'm pretty sure it was because of an attempt to use java 1.7, which does not support the new java time classes such as java.time.Instant. Foundation is not going to attempt to support 1.7, only 1.8 and above at this time.
